### ISSUE TITLE
Pages not displaying contents

### ISSUE THREAD

**Issue by sovello** [patmark/care2x-tz#3]
Hi!
I installed this repo and was trying to play around and found the pharmacy, System Admin and Registration pages do not work at all.
Once you click the URL you get a blank page. as for the System Admin page the problem was the script was calling a function that is undefined.
For the rest I couldn't figure out. 
Am hacking around creating and adding new modules to care2x.

Cheers

**Comment by patmark** [comment]
Hello,

Some scripts may not work due to db mismatch.

*Patrick  N  Mark*

*IT Consultant Computer Systems, Networks and Software*
